import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author izzet_oğuz_bozak
 */

// Önemli bir sorun olarak...
//Geri al butonunda en sonki hali programın içinde kalıyor.
//Geri alma yazma ardından tekrar geri alma yapıldığında eski bir durum dönderiyor
//Bunun sebebi addDocumentListener fonksiyonunun işlem yapıldıktan sonraki halini
// kaydetmesidir. a ekleniyorsa fonksiyon a'yı eklenmiş haliyle getiriyor.

public class Arayuz extends javax.swing.JFrame implements Observer {
    
    Metin metinNesnesi = new Metin();
    hafizaMemento hafiza = new hafizaMemento();
    
    @Override
    public void update(Observable observable){

        // Observer design pattern gereği bu metot bir uyarı mesajı gönderir.
        // Dosya kaydedilmeden kapatılıyorsa, bir uyarı mesajı gönderilebilir.
        // yapılan işlemler tasarım desenine gerek kalmadan dosyayı kapat
        // butonunun içine yazdım.
    }
    
    
    
    public Arayuz() {
        initComponents();
        dosyaListesi.setVisible(false);
        listeAlti.setVisible(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2); 
        
        metinPanel.setVisible(false);
        metinGirlabel.setVisible(false);
        panelDosyaAdi.setVisible(false);
        kelimeBulPanel.setVisible(false);
        kelimeDegistirPanel.setVisible(false);
        
        metin.getDocument().addDocumentListener(new DocumentListener() {
        public void insertUpdate(DocumentEvent e) {
            if ( metinNesnesi.getMod()==true ){
            if(metinNesnesi.getGeriAlaBasilmaSonrasiEklenirse()==true){
                hafiza.hafizaMementoEkle(hafiza.getSonCikarilanListeMetinMemento());
                metinNesnesi.setGeriAlaBasilmaSonrasiEklenirse(false);
            } 
            MetinMemento metin_memento = new MetinMemento();
            metin_memento.setMetinAdi( dosyaAdi.getText() );
            metinNesnesi.setMod(false);
            metin_memento.setSozcukler( metin_memento.metinParcala( metin.getText() ) );
            metinNesnesi.setMod(true);
            hafiza.hafizaMementoEkle(metin_memento);
            metinNesnesi.setGeriAlSayisi(0);
            metinNesnesi.setGeriAlaBasilmaSonrasiEklenirse(false);
            
        }}

        public void removeUpdate(DocumentEvent e) {
            if ( metinNesnesi.getMod()==true ){
                if(metinNesnesi.getGeriAlaBasilmaSonrasiEklenirse()==true){
                hafiza.hafizaMementoEkle(hafiza.getSonCikarilanListeMetinMemento());
                metinNesnesi.setGeriAlaBasilmaSonrasiEklenirse(false);
            } 
            MetinMemento metin_memento = new MetinMemento();
            metin_memento.setMetinAdi(dosyaAdi.getText());
            metinNesnesi.setMod(false);
            metin_memento.setSozcukler( metin_memento.metinParcala(metin.getText()) );
            metinNesnesi.setMod(true);
            hafiza.hafizaMementoEkle(metin_memento);
            metinNesnesi.setGeriAlSayisi(0);
            
        }}

        public void changedUpdate(DocumentEvent e) {
            if ( metinNesnesi.getMod()==true ){
                if(metinNesnesi.getGeriAlaBasilmaSonrasiEklenirse()==true){
                hafiza.hafizaMementoEkle(hafiza.getSonCikarilanListeMetinMemento());
                metinNesnesi.setGeriAlaBasilmaSonrasiEklenirse(false);
            } 
            MetinMemento metin_mementox = new MetinMemento();
            metin_mementox.setMetinAdi(dosyaAdi.getText());
            metinNesnesi.setMod(false);
            metin_mementox.setSozcukler( metin_mementox.metinParcala(metin.getText()) );
            metinNesnesi.setMod(true);
            hafiza.hafizaMementoEkle(metin_mementox);
            metinNesnesi.setGeriAlSayisi(0);
        }}
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        popupMenu3 = new java.awt.PopupMenu();
        popupMenu4 = new java.awt.PopupMenu();
        popupMenu5 = new java.awt.PopupMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        menu = new javax.swing.JPanel();
        dosyaOlustur = new javax.swing.JButton();
        dosyaAc = new javax.swing.JButton();
        dosyaKaydet = new javax.swing.JButton();
        dosyaKapat = new javax.swing.JButton();
        metinPanel = new javax.swing.JPanel();
        metinGirlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        metin = new javax.swing.JTextArea();
        dosyaListesi = new java.awt.List();
        listeAlti = new javax.swing.JLabel();
        panelDosyaAdi = new javax.swing.JPanel();
        dosyaAdi = new javax.swing.JTextField();
        labelDosyaAdi = new javax.swing.JLabel();
        acButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        kelimeBulPanel = new javax.swing.JPanel();
        kelimeBul = new javax.swing.JButton();
        bulunacakKelime = new javax.swing.JTextField();
        kelimeKontrolButonu = new javax.swing.JButton();
        geriAlButonu = new javax.swing.JButton();
        kelimeDegistirPanel = new javax.swing.JPanel();
        degistir = new javax.swing.JTextField();
        degistirButon = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        popupMenu3.setLabel("popupMenu3");

        popupMenu4.setLabel("popupMenu4");

        popupMenu5.setLabel("popupMenu5");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dosyaOlustur.setText("Dosya Oluştur");
        dosyaOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaOlusturActionPerformed(evt);
            }
        });

        dosyaAc.setText("Dosya Aç");
        dosyaAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaAcActionPerformed(evt);
            }
        });

        dosyaKaydet.setText("Dosya Kaydet");
        dosyaKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaKaydetActionPerformed(evt);
            }
        });

        dosyaKapat.setText("Dosya Kapat");
        dosyaKapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaKapatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dosyaKaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dosyaAc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dosyaOlustur, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(dosyaKapat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dosyaOlustur)
                .addGap(18, 18, 18)
                .addComponent(dosyaAc)
                .addGap(18, 18, 18)
                .addComponent(dosyaKaydet)
                .addGap(18, 18, 18)
                .addComponent(dosyaKapat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        metinGirlabel.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        metinGirlabel.setText("Metni aşağı giriniz");

        metin.setColumns(20);
        metin.setRows(5);
        jScrollPane1.setViewportView(metin);

        javax.swing.GroupLayout metinPanelLayout = new javax.swing.GroupLayout(metinPanel);
        metinPanel.setLayout(metinPanelLayout);
        metinPanelLayout.setHorizontalGroup(
            metinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metinPanelLayout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(metinGirlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
            .addGroup(metinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        metinPanelLayout.setVerticalGroup(
            metinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, metinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(metinGirlabel)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        dosyaListesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaListesiActionPerformed(evt);
            }
        });

        listeAlti.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        listeAlti.setText("   Dosya Listesi");

        dosyaAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaAdiActionPerformed(evt);
            }
        });

        labelDosyaAdi.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        labelDosyaAdi.setText("Dosya adını buraya girin");

        acButton.setText("Aç");
        acButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDosyaAdiLayout = new javax.swing.GroupLayout(panelDosyaAdi);
        panelDosyaAdi.setLayout(panelDosyaAdiLayout);
        panelDosyaAdiLayout.setHorizontalGroup(
            panelDosyaAdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDosyaAdiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelDosyaAdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDosyaAdi)
                    .addGroup(panelDosyaAdiLayout.createSequentialGroup()
                        .addComponent(dosyaAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(acButton)))
                .addContainerGap())
        );
        panelDosyaAdiLayout.setVerticalGroup(
            panelDosyaAdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDosyaAdiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelDosyaAdiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dosyaAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDosyaAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exitButton.setBackground(new java.awt.Color(204, 0, 0));
        exitButton.setText("ÇIKIŞ");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        kelimeBul.setText("Kelime bul");
        kelimeBul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelimeBulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kelimeBulPanelLayout = new javax.swing.GroupLayout(kelimeBulPanel);
        kelimeBulPanel.setLayout(kelimeBulPanelLayout);
        kelimeBulPanelLayout.setHorizontalGroup(
            kelimeBulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelimeBulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kelimeBulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kelimeBul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(bulunacakKelime)))
        );
        kelimeBulPanelLayout.setVerticalGroup(
            kelimeBulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kelimeBulPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bulunacakKelime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kelimeBul)
                .addGap(183, 183, 183))
        );

        kelimeKontrolButonu.setText("Kelimeleri Kontrol Et");
        kelimeKontrolButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelimeKontrolButonuActionPerformed(evt);
            }
        });

        geriAlButonu.setText("Geri Al");
        geriAlButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriAlButonuActionPerformed(evt);
            }
        });

        degistirButon.setText("Kelimeyi Değiştir");
        degistirButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degistirButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kelimeDegistirPanelLayout = new javax.swing.GroupLayout(kelimeDegistirPanel);
        kelimeDegistirPanel.setLayout(kelimeDegistirPanelLayout);
        kelimeDegistirPanelLayout.setHorizontalGroup(
            kelimeDegistirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelimeDegistirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kelimeDegistirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(degistir)
                    .addComponent(degistirButon, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
        );
        kelimeDegistirPanelLayout.setVerticalGroup(
            kelimeDegistirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelimeDegistirPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(degistir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(degistirButon)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kelimeKontrolButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(geriAlButonu, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                        .addComponent(dosyaListesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(metinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(panelDosyaAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kelimeBulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(kelimeDegistirPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(listeAlti, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(geriAlButonu)
                        .addGap(18, 18, 18)
                        .addComponent(kelimeKontrolButonu)
                        .addGap(26, 26, 26)
                        .addComponent(exitButton)
                        .addGap(60, 60, 60)
                        .addComponent(dosyaListesi, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listeAlti, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(metinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(panelDosyaAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(kelimeBulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kelimeDegistirPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void dosyaAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaAcActionPerformed
        // TODO add your handling code here:
        metinNesnesi.setMod(false);
        dosyaListesi.setVisible(true);
        metinPanel.setVisible(false);
        panelDosyaAdi.setVisible(true);
        listeAlti.setVisible(true);
        acButton.setVisible(true);
        dosyaListesi.removeAll();
        //kelimeBulPanel.setVisible(true);
        //File klasor = new File("C:/Users/batma/Documents/NetBeansProjects/OOP_proje1");
        String userDirectory = System.getProperty("user.dir");
        File klasor = new File(userDirectory);
   
        String dosyalar[] = klasor.list();
              
        for (String dosyalar1 : dosyalar)
        if( !dosyalar1.equals("words.txt") && dosyalar1.length()>4 && 
         dosyalar1.substring(dosyalar1.length()-3, dosyalar1.length()).equals("txt") )   dosyaListesi.add(dosyalar1);
        
        if(dosyaAdi.getText().equals("")){
        JOptionPane.showMessageDialog(this,  "Dosya adını belirtilen yere yazınız ve tıklayınız", "Bilgi",  JOptionPane.INFORMATION_MESSAGE);
        }
        metinNesnesi.setMod(true);
    }//GEN-LAST:event_dosyaAcActionPerformed

    private void dosyaKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaKaydetActionPerformed
            metinNesnesi.setMod(false);
        String yazilacak = metin.getText();
    String path=dosyaAdi.getText()+".txt";
        try {
      FileWriter myWriter = new FileWriter(path);
      myWriter.write(yazilacak);
      myWriter.close();
      
    } catch (IOException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
        metin.setText("");
        dosyaAdi.setText("");
        JOptionPane.showMessageDialog(this,  "Dosya başarıyla kaydedildi", "Bilgi",  JOptionPane.INFORMATION_MESSAGE);
        metinNesnesi.setMod(true);
    }//GEN-LAST:event_dosyaKaydetActionPerformed

    private void dosyaOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaOlusturActionPerformed
                            // TODO add your handling code here:
        metinNesnesi.setMod(false);
        metinPanel.setVisible(true);
        metinGirlabel.setVisible(true);
        kelimeBulPanel.setVisible(true);
        metin.setText("");
        panelDosyaAdi.setVisible(true);
        dosyaAdi.setVisible(true);
        acButton.setVisible(false);
        
        FileWriter writer = null;
        try {
        String ad=dosyaAdi.getText();
        String path=ad+".txt";
            
        writer  = new FileWriter(path);
          
            
        }    
        catch (IOException ex) {        
            Logger.getLogger(Arayuz.class.getName()).log(Level.SEVERE, null, ex);
        }        
       
        finally{
            if (writer != null) {
                try {
                    writer.close();
                } catch (IOException ex) {
                    System.out.println("Dosya Kapatılırken bir hata oluştu...");
                }

            }
        }
        
    MetinMemento metin_memento = new MetinMemento();
            metin_memento.setMetinAdi( dosyaAdi.getText() );
            metin_memento.setSozcukler( metin_memento.metinParcala( "" ) );
             hafiza.hafizaMementoEkle(metin_memento);
             metinNesnesi.setMod(true);
             metinNesnesi.setGeriAlSayisi(0);
    }//GEN-LAST:event_dosyaOlusturActionPerformed

    private void dosyaKapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaKapatActionPerformed
        // TODO add your handling code here:
        
        //metin kaydetme kontrolü için dosya açtık.
        // Observer design pattern kullanıldı.
        
        try {
            
        String veriTabanındakiDosyaAdi=dosyaAdi.getText();
        String path=  veriTabanındakiDosyaAdi +".txt";
      File myObj = new File(path);
      Scanner myReader = new Scanner(myObj);
      
      ArrayList<String> satirlar = new ArrayList<String>();
      while (myReader.hasNextLine()) {
        satirlar.add(myReader.nextLine());
      }  
      
      String butunSatirlar="";
      for(String satir:satirlar) butunSatirlar= butunSatirlar + satir;

      Text yaziliMetin= new Text(metin.getText());    // most important part
      yaziliMetin.ekle( this );
      //yaziliMetin.kaydedildiMiKontrolEt(butunSatirlar);
              
      
      if(  yaziliMetin.kaydedildiMiKontrolEt(butunSatirlar) ) {
        metinPanel.setVisible(false);
        metinGirlabel.setVisible(false);
        kelimeBulPanel.setVisible(false);
        kelimeDegistirPanel.setVisible(false);
        panelDosyaAdi.setVisible(false);
        dosyaListesi.setVisible(false);
        listeAlti.setVisible(false);
      }
      else {
          
          
          Object[] options = { "Yinede dosyayı kapat",
                    "İptal" };
  int choice = JOptionPane.showOptionDialog(this, 
      "Dosyayı kaydetmediniz!", 
      "Bilgi", 
      JOptionPane.YES_NO_OPTION, 
      JOptionPane.QUESTION_MESSAGE, 
      null, 
      options, 
      options[0]);

  // interpret the user's choice
  if (choice == JOptionPane.YES_OPTION)
  {
    metinPanel.setVisible(false);
    metinGirlabel.setVisible(false);
    kelimeBulPanel.setVisible(false);
    kelimeDegistirPanel.setVisible(false);
    panelDosyaAdi.setVisible(false);
    dosyaListesi.setVisible(false);
    listeAlti.setVisible(false);
    metinNesnesi.setGeriAlSayisi(0);
    hafiza.hafizaMementoTemizle(); // Geri Al temizleniyor.
  }
   
      }
      
      
      
       
      myReader.close();
    } catch (FileNotFoundException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
     
       
    }//GEN-LAST:event_dosyaKapatActionPerformed

    private void dosyaAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosyaAdiActionPerformed

    private void dosyaListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaListesiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosyaListesiActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    
    private void kelimeBulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelimeBulActionPerformed
        // TODO add your handling code here:
        metinNesnesi.setMod(false);
        metinNesnesi.setMetinAdi(dosyaAdi.getText());
        metinNesnesi.setSozcukler(metinNesnesi.metinParcala(metin.getText()));
        if(metinNesnesi.kelimeBul(bulunacakKelime.getText())==null){
            JOptionPane.showMessageDialog(this,  "Kelime Bulunamadı", "Bilgi",  JOptionPane.INFORMATION_MESSAGE);
            bulunacakKelime.setText("");
            
        }
        else{
            JOptionPane.showMessageDialog(this,  "Aranan Kelime Bulundu!", "Bilgi",  JOptionPane.INFORMATION_MESSAGE);
            kelimeBulPanel.setVisible(false);
            kelimeDegistirPanel.setVisible(true);
        }

        metinNesnesi.setMod(true);
    }//GEN-LAST:event_kelimeBulActionPerformed

    private void degistirButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degistirButonActionPerformed
        // TODO add your handling code here:
        metinNesnesi.setMod(false);
              ArrayList<Integer> bulunacakKelimeIndexListesi =
                metinNesnesi.kelimeBul(bulunacakKelime.getText());  
          metinNesnesi.kelimeDegistir(degistir.getText(), bulunacakKelimeIndexListesi);
          metin.setText(metinNesnesi.metinBirlestir(metinNesnesi.getSozcukler()));
          JOptionPane.showMessageDialog(this,  "Kelime Başarıyla Değiştirildi", "Bilgi",  JOptionPane.INFORMATION_MESSAGE);
        metinNesnesi.setMod(true);     
    }//GEN-LAST:event_degistirButonActionPerformed

    private void kelimeKontrolButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelimeKontrolButonuActionPerformed
        // TODO add your handling code here:
        metinNesnesi.setMod(false);
        metinNesnesi.setMetinAdi(dosyaAdi.getText());
        metinNesnesi.setSozcukler( metinNesnesi.metinParcala(metin.getText()) );
        ArrayList<String> sozlukArrayList = new ArrayList<String>();
        try {
        String path="words.txt";
      File myObj = new File(path);
      Scanner myReader = new Scanner(myObj);
      while (myReader.hasNextLine()) sozlukArrayList.add( myReader.nextLine() );
      myReader.close(); }
     catch (FileNotFoundException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }

       int i = 0;    // Iterator design pattern burada kullanıldı.
    for (Iterator iter = metinNesnesi.getIteratorSozcukler(); iter.hasNext(); i++) {
        String nextString=(String) iter.next();
        if( metinNesnesi.kelimeHataliMi(nextString,sozlukArrayList) )
           metinNesnesi.getSozcukler().set(i, metinNesnesi.singleTransposition
        (nextString,sozlukArrayList) ); 
    }
       metin.setText(metinNesnesi.metinBirlestir(metinNesnesi.getSozcukler())); 
       metinNesnesi.setMod(true);
    }//GEN-LAST:event_kelimeKontrolButonuActionPerformed

    private void geriAlButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriAlButonuActionPerformed

        /*
        metinNesnesi.setMetinAdi(dosyaAdi.getText());
        metinNesnesi.setSozcukler( metinNesnesi.metinParcala(metin.getText()) );
        String sonHarfSilinen=yonlendiriciCommandDesignPattern.yonlendir //Command Design Pattern
        (new geriAlCommand(),metinNesnesi.getSozcukler().getLast()); // Burada kullanılmıştır.
        metinNesnesi.getSozcukler().set(metinNesnesi.getSozcukler().size()-1, sonHarfSilinen);
        metin.setText(metinNesnesi.metinBirlestir(metinNesnesi.getSozcukler()));
        */
        //Yukarıdaki Commands Design pattern içindir. Aşağı yoruma alınıp yukarudaki açılırsa,
        // Comment Design pattern çalıştırılabilir.

        
        if(metinNesnesi.getGeriAlSayisi()==0){
                    hafiza.getListeMetinMemento().removeLast();
                    int geriAlsayisi=metinNesnesi.getGeriAlSayisi();
                    metinNesnesi.setGeriAlSayisi(geriAlsayisi+1);
                }
        metinNesnesi.setMod(false);
        metinNesnesi.setMetinAdi(dosyaAdi.getText());
        metinNesnesi.setSozcukler( metinNesnesi.metinParcala(metin.getText()) );
        
       
        metinNesnesi.geriDonMemento(hafiza.sonVersiyonuGetir());
        metin.setText(metinNesnesi.metinBirlestir(metinNesnesi.getSozcukler()));
         metinNesnesi.setMod(true);
         metinNesnesi.setGeriAlaBasilmaSonrasiEklenirse(true);

    }//GEN-LAST:event_geriAlButonuActionPerformed

    private void acButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acButtonActionPerformed
        // TODO add your handling code here:
        metinNesnesi.setMod(false);

        
        
        
        acButton.setVisible(true);
        dosyaListesi.setVisible(true);
        metin.setVisible(true);
        metinPanel.setVisible(true);
        panelDosyaAdi.setVisible(true);
        listeAlti.setVisible(true);
        kelimeBulPanel.setVisible(true);
        //File klasor = new File("C:/Nesne3Project");
        //String userDirectory = System.getProperty("user.dir");
        //File klasor = new File(userDirectory);
       
        //System.out.println(userDirectory);
        /*String dosyalar[] = klasor.list();
        for (String dosyalar1 : dosyalar){
        if(!dosyalar1.equals("words.txt") && dosyalar1.length()>4 &&
                dosyalar1.substring(dosyalar1.length()-3, dosyalar1.length()).equals("txt")  ){
      
            //dosyaListesi.add(dosyalar1);
        }
        }*/
        
        
        try {
        
        String ad=dosyaAdi.getText();
        String path=ad+".txt";
      File myObj = new File(path);
      Scanner myReader = new Scanner(myObj);
      
      ArrayList<String> satirlar = new ArrayList<String>();
      while (myReader.hasNextLine()) {
        satirlar.add(myReader.nextLine());
      }  
      
      String butunSatirlar="";
      for(String satir:satirlar) butunSatirlar= butunSatirlar + satir;
      metin.setText(butunSatirlar);
      myReader.close();
    } catch (FileNotFoundException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
        
        
        // Geri alma işlemini burada gerçekleştirebiliriz.

         MetinMemento metin_memento = new MetinMemento();
            metin_memento.setMetinAdi( dosyaAdi.getText() );
            metin_memento.setSozcukler( metin_memento.metinParcala( metin.getText() ) );
             hafiza.hafizaMementoEkle(metin_memento);
             metinNesnesi.setMod(true);
    }//GEN-LAST:event_acButtonActionPerformed
    /*public Metin don(){
        Metin deneme=new Metin(dosyaAdi.getText(),metin.getText());
        return deneme;
    }
    public ArrayList<Integer> kelimeDon(){
        ArrayList<Integer> x =don().kelimeBul(bulunacakKelime.getText());
        return x;
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Arayuz arayuz = new Arayuz();
               arayuz.setVisible(true);
        
                
            }
        });
    }
    
    public File[] finder( String dirName){
        File dir = new File(dirName);

        return dir.listFiles(new FilenameFilter() { 
                 public boolean accept(File dir, String filename)
                      { return filename.endsWith(".txt"); }
        } );

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acButton;
    private javax.swing.JTextField bulunacakKelime;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField degistir;
    private javax.swing.JButton degistirButon;
    private javax.swing.JButton dosyaAc;
    private javax.swing.JTextField dosyaAdi;
    private javax.swing.JButton dosyaKapat;
    private javax.swing.JButton dosyaKaydet;
    private java.awt.List dosyaListesi;
    private javax.swing.JButton dosyaOlustur;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton geriAlButonu;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kelimeBul;
    private javax.swing.JPanel kelimeBulPanel;
    private javax.swing.JPanel kelimeDegistirPanel;
    private javax.swing.JButton kelimeKontrolButonu;
    private javax.swing.JLabel labelDosyaAdi;
    private javax.swing.JLabel listeAlti;
    private javax.swing.JPanel menu;
    private javax.swing.JTextArea metin;
    private javax.swing.JLabel metinGirlabel;
    private javax.swing.JPanel metinPanel;
    private javax.swing.JPanel panelDosyaAdi;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private java.awt.PopupMenu popupMenu3;
    private java.awt.PopupMenu popupMenu4;
    private java.awt.PopupMenu popupMenu5;
    // End of variables declaration//GEN-END:variables
}